import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.scss";

interface ILayout {
  children: React.ReactNode;
}
function Layout({ children }: ILayout) {
  return (
    <div>
      <Head>
        <title>Bookmark Website</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>{children}</main>
      {/* FOOTER */}
    </div>
  );
}

export default Layout;
